import React, {ChangeEvent, FormEvent, useState} from "react";
import {useRouter} from "next/router";
import {register} from "../requests";
import Head from "next/head";

export default function Register() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const router = useRouter();

    const handleSubmit = (e: FormEvent) => {
        e.preventDefault();
        register(email, password).then(resp => {
            if (resp.data.errors) throw new Error(resp.data.errors[0].message);
            if (resp.status === 200 && resp.data.data.register.success) {
                router.push({
                    pathname: '/',
                    query: { uuid: resp.data.data.register.user.uuid }
                });
            }
        })
    }

    const handleEmailChange = (e: ChangeEvent<HTMLInputElement>) => {
        e.preventDefault();
        setEmail(e.target.value);
    }

    const handlePasswordChange = (e: ChangeEvent<HTMLInputElement>) => {
        e.preventDefault();
        setPassword(e.target.value);
    }

    return (
        <>
            <Head>
                <title>{'Job Scraper'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <form onSubmit={handleSubmit}>
                Email: <input type='email' onChange={handleEmailChange}/><br/>
                Password: <input type='password' onChange={handlePasswordChange}/><br/>
                <button type='submit'>Submit</button>
            </form>
            <br/>
            <br/>
            <button onClick={() => router.replace('/login')}>Login</button>
        </>
    );
}